Repository DO-SOPT-33rd-CDS-1/LongBlack_Android, pull requests merged in 2023-11, with the labels that each got.

#7 [init] 프로젝트 초기세팅
  app/src/main/res/drawable/ic_article_arrow_left.png
  app/src/main/res/drawable/ic_article_arrow_right.png
  app/src/main/res/drawable/ic_article_bookmark_off.png
  app/src/main/res/drawable/ic_article_bookmark_on.png
  app/src/main/res/drawable/ic_article_econdary_on.png
  app/src/main/res/drawable/ic_article_readmark.png
  app/src/main/res/drawable/ic_article_secondary_off.png
  app/src/main/res/drawable/ic_article_sticker_off.png
  app/src/main/res/drawable/ic_article_sticker_on.png
  app/src/main/res/drawable/ic_event_arrow_left.png
  app/src/main/res/drawable/ic_event_arrow_right.png
  app/src/main/res/drawable/ic_home_clock.png
  app/src/main/res/drawable/ic_home_gotolibrary.png
  app/src/main/res/drawable/ic_home_gotonote.png
  app/src/main/res/drawable/ic_library_exc_active.png
  app/src/main/res/drawable/ic_library_exc_unactive.png
  app/src/main/res/drawable/ic_library_sticker_off.png
  app/src/main/res/drawable/ic_library_sticker_on.png
  app/src/main/res/drawable/ic_note_bookmark_off.png
  app/src/main/res/drawable/ic_note_bookmark_on.png
  app/src/main/res/drawable/ic_note_search.png
  app/src/main/res/drawable/img_article_profile.png
  app/src/main/res/drawable/img_event_blue.jpg
  app/src/main/res/drawable/img_event_bottom.png
  app/src/main/res/drawable/img_event_green.jpg
  app/src/main/res/drawable/img_event_red.jpg
  app/src/main/res/drawable/img_home_note_structure.jpg
  app/src/main/res/drawable/img_home_thumbnail.png
  app/src/main/res/drawable/img_library_card.png
  app/src/main/res/drawable/img_navigationbar.jpg
  app/src/main/res/drawable/img_note_acidleague.jpg
  app/src/main/res/drawable/img_note_barista.jpg
  app/src/main/res/drawable/img_note_kolonsports.jpg
  app/src/main/res/drawable/img_note_learntopractice.jpg
  app/src/main/res/drawable/img_note_mustoy.jpg
  app/src/main/res/drawable/img_note_numberbar.jpg
  app/src/main/res/drawable/img_note_opengallery.jpg
  app/src/main/res/drawable/img_note_sushi.png
  app/src/main/res/drawable/img_release_author.jpg
  app/src/main/res/drawable/img_release_lck.png
  app/src/main/res/drawable/img_release_wendy.jpg
  app/src/main/res/drawable/img_top_navigation.jpg
  app/src/main/res/drawable/line_black_android.png
  app/src/main/res/drawable/line_bold_android.png
  app/src/main/res/drawable/line_thin_android.png
Labels: init, 연진

#5 [init] 프로젝트 초기세팅
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/values/colors.xml
  app/src/main/res/values/typography.xml
Labels: init, 명지

#12 [ui] 노트 리스트 뷰 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/longdroid/presentation/note_list/NoteListActivity.kt
  app/src/main/java/com/example/longdroid/presentation/note_list/adapter/NoteListFooterAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/note_list/adapter/NoteListHeaderAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/note_list/adapter/NoteListItemAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/note_list/viewholder/FooterViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/note_list/viewholder/HeaderViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/note_list/viewholder/NoteListViewHolder.kt
  app/src/main/res/drawable/ic_divide.xml
  app/src/main/res/drawable/shape_border_32.xml
  app/src/main/res/drawable/shape_border_43.xml
  app/src/main/res/drawable/shape_border_43_stroke.xml
  app/src/main/res/drawable/shape_border_8_bottom.xml
  app/src/main/res/layout/activity_note_list.xml
  app/src/main/res/layout/item_note.xml
  app/src/main/res/layout/item_note_list_footer.xml
  app/src/main/res/layout/item_note_list_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/typography.xml
Labels: ui, 명지

#14 [feat] 아티클 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/longdroid/presentation/MainActivity.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticleActivity.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticlelViewModel.kt
  app/src/main/res/drawable/ic_arrow_left_white.xml
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_article_main.xml
  app/src/main/res/layout/item_article_title.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ui, 준희

#21 [ui] Home 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/longdroid/data/di/ApiFactory.kt
  app/src/main/java/com/example/longdroid/presentation/HomeActivity.kt
  app/src/main/java/com/example/longdroid/presentation/MainActivity.kt
  app/src/main/java/com/example/longdroid/presentation/library/LibraryActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/NoteListActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/adapter/NoteListFooterAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/adapter/NoteListHeaderAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/adapter/NoteListItemAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/FooterViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/HeaderViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/NoteListViewHolder.kt
  app/src/main/res/drawable-xhdpi/ic_go_to_library.png
  app/src/main/res/drawable-xhdpi/ic_go_to_note.png
  app/src/main/res/drawable-xhdpi/img_home_title.png
  app/src/main/res/drawable-xxhdpi/ic_go_to_library.png
  app/src/main/res/drawable-xxhdpi/ic_go_to_note.png
  app/src/main/res/drawable-xxhdpi/img_home_title.png
  app/src/main/res/drawable/ic_go_to_library.png
  app/src/main/res/drawable/ic_go_to_note.png
  app/src/main/res/drawable/img_home_title.png
  app/src/main/res/drawable/line_bold_white.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: ui, 연진

#24 [feat] Library stamp 서버 통신
  app/build.gradle
  app/src/main/java/com/example/longdroid/data/di/ApiFactory.kt
  app/src/main/java/com/example/longdroid/data/di/LibraryApiService.kt
  app/src/main/java/com/example/longdroid/data/di/LibraryResponse.kt
  app/src/main/java/com/example/longdroid/presentation/library/LibraryActivity.kt
Labels: feat, 연진

#23 [feat] 좋아요 누르는 서버 통신 구현
  app/src/main/java/com/example/longdroid/data/di/ApiFactory.kt
  app/src/main/java/com/example/longdroid/data/model/request/RequestLike.kt
  app/src/main/java/com/example/longdroid/data/model/response/ResponseNoteList.kt
  app/src/main/java/com/example/longdroid/data/service/LikedService.kt
  app/src/main/java/com/example/longdroid/presentation/library/LibraryActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/adapter/NoteListItemAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/NoteListViewHolder.kt
  app/src/main/res/layout/item_note.xml
Labels: feat, 명지

#27 [feat] 노트 리스트 뷰 서버 통신
  app/src/main/java/com/example/longdroid/data/di/ApiFactory.kt
  app/src/main/java/com/example/longdroid/data/model/response/LibraryResponse.kt
  app/src/main/java/com/example/longdroid/data/model/response/ResponseNoteList.kt
  app/src/main/java/com/example/longdroid/data/service/LibraryApiService.kt
  app/src/main/java/com/example/longdroid/data/service/NoteListService.kt
  app/src/main/java/com/example/longdroid/presentation/library/LibraryActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/NoteListActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/NoteListViewModel.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/adapter/NoteListHeaderAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/adapter/NoteListItemAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/HeaderViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/NoteListViewHolder.kt
  app/src/main/res/drawable-xhdpi/img_note_arc.png
  app/src/main/res/drawable-xxhdpi/img_note_arc.png
  app/src/main/res/drawable/img_note_arc.png
Labels: feat, pull request, 명지

#26 [feat] 아티클 뷰 서버통신
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/longdroid/LongBlackApplication.kt
  app/src/main/java/com/example/longdroid/data/datasource/LongBlackStorage.kt
  app/src/main/java/com/example/longdroid/data/model/request/RequestArticleBookMarkDto.kt
  app/src/main/java/com/example/longdroid/data/model/request/RequestArticleLikeDto.kt
  app/src/main/java/com/example/longdroid/data/model/request/RequestArticleStampDto.kt
  app/src/main/java/com/example/longdroid/data/model/response/ResponseArticleDto.kt
  app/src/main/java/com/example/longdroid/data/service/ArticleService.kt
  app/src/main/java/com/example/longdroid/di/ApiFactory.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticleActivity.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticleParagraphAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticleParagraphViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticleTitleAdapter.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticleTitleViewHolder.kt
  app/src/main/java/com/example/longdroid/presentation/article/ArticlelViewModel.kt
  app/src/main/java/com/example/longdroid/presentation/library/LibraryActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/NoteListActivity.kt
  app/src/main/java/com/example/longdroid/presentation/notelist/viewholder/NoteListViewHolder.kt
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/item_article_body.xml
  app/src/main/res/layout/item_article_main.xml
  app/src/main/res/layout/item_article_subtitle.xml
  app/src/main/res/layout/item_article_title.xml
Labels: feat, pull request, 준희
